### ISSUE TITLE
Добавить в раздел 3.27 картинки в дополнение к pdf-ке

### ISSUE THREAD

**Issue by akhazipov** [theLonelyWarrior/fixInstructions#12]
архив в аттаче
[3.27.zip](https://github.com/theLonelyWarrior/fixInstructions/files/1144362/3.27.zip)

**Comment by theLonelyWarrior** [comment]
Добавил, спасибо!
![3 27-0](https://user-images.githubusercontent.com/30047028/28162514-086ab426-67d0-11e7-9ffa-f21b2fee7e4e.jpg)
![3 27-1](https://user-images.githubusercontent.com/30047028/28162510-08677dec-67d0-11e7-9e54-a5b646726868.jpg)
![3 27-2](https://user-images.githubusercontent.com/30047028/28162511-0868339a-67d0-11e7-99c6-431091ea87f6.jpg)
![3 27-3](https://user-images.githubusercontent.com/30047028/28162512-086957ac-67d0-11e7-8d50-cf4149f4b7ee.jpg)
![3 27-4](https://user-images.githubusercontent.com/30047028/28162515-086bd752-67d0-11e7-88fe-11fe22a9a09d.jpg)
![3 27-5](https://user-images.githubusercontent.com/30047028/28162513-08696d32-67d0-11e7-8984-abafb6495646.jpg)
![3 27-6](https://user-images.githubusercontent.com/30047028/28162517-0880b0f0-67d0-11e7-8024-f9e0c452cb34.jpg)
![3 27-7](https://user-images.githubusercontent.com/30047028/28162518-0881a71c-67d0-11e7-954a-b3291cbee9b3.jpg)
