### ISSUE TITLE
методичка по 3.27

### ISSUE THREAD

**Issue by shurilla1987** [theLonelyWarrior/fixInstructions#5]
Методичка по типичным ошибкам при фиксации «Стоянка запрещена» (знак 3.27): http://files.srvdev.ru/download/y/tipichnye-oshibki-3.27.pdf

**Comment by theLonelyWarrior** [comment]
[tipichnye-oshibki-3.27.pdf](https://github.com/theLonelyWarrior/fixInstructions/files/1141289/tipichnye-oshibki-3.27.pdf)
Залито
