### ISSUE TITLE
в Q4 надо бы описать общие требования

### ISSUE THREAD

**Issue by shurilla1987** [theLonelyWarrior/fixInstructions#8]
https://github.com/theLonelyWarrior/fixInstructions/wiki/FAQ#Q4 

хорошо бы указать, что на каждой фотке должен быть виден ГРЗ, все ведро целиком и т.п.
Ну и короткую справку на тему того, для каких нарушений какие номера фоток должны быть одинаковыми и т.п.

**Comment by theLonelyWarrior** [comment]
Добавил там ссылки на методички
